//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartax.Web.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Smartax.Web.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrastre al grupo o reordenar.
        /// </summary>
        internal static string RadGridClientSettingsClientMessagesDragToGroupOrReorder {
            get {
                return ResourceManager.GetString("RadGridClientSettingsClientMessagesDragToGroupOrReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrastre para redimensionar.
        /// </summary>
        internal static string RadGridClientSettingsClientMessagesDragToResize {
            get {
                return ResourceManager.GetString("RadGridClientSettingsClientMessagesDragToResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Traer aqui para reordenar.
        /// </summary>
        internal static string RadGridClientSettingsClientMessagesDropHereToReorder {
            get {
                return ResourceManager.GetString("RadGridClientSettingsClientMessagesDropHereToReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pág: &lt;b&gt;{0}&lt;/b&gt; de &lt;b&gt;{1}&lt;/b&gt; Páginas.
        /// </summary>
        internal static string RadGridClientSettingsClientMessagesPagerTooltipFormatString {
            get {
                return ResourceManager.GetString("RadGridClientSettingsClientMessagesPagerTooltipFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraer grupo.
        /// </summary>
        internal static string RadGridGroupingSettingsCollapseTooltip {
            get {
                return ResourceManager.GetString("RadGridGroupingSettingsCollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ... Continuación del grupo de la página anterior.
        /// </summary>
        internal static string RadGridGroupingSettingsGroupContinuedFormatString {
            get {
                return ResourceManager.GetString("RadGridGroupingSettingsGroupContinuedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo continua en la siguiente página....
        /// </summary>
        internal static string RadGridGroupingSettingsGroupContinuesFormatString {
            get {
                return ResourceManager.GetString("RadGridGroupingSettingsGroupContinuesFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrando {0} de {1} items..
        /// </summary>
        internal static string RadGridGroupingSettingsGroupSplitDisplayFormat {
            get {
                return ResourceManager.GetString("RadGridGroupingSettingsGroupSplitDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrastrar fuera de la barra para desagrupar.
        /// </summary>
        internal static string RadGridGroupingSettingsUnGroupTooltip {
            get {
                return ResourceManager.GetString("RadGridGroupingSettingsUnGroupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrastre un encabezado de una columna hasta aca para agrupar por dicha columna.
        /// </summary>
        internal static string RadGridGroupPanelText {
            get {
                return ResourceManager.GetString("RadGridGroupPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraer.
        /// </summary>
        internal static string RadGridHierarchySettingsCollapseTooltip {
            get {
                return ResourceManager.GetString("RadGridHierarchySettingsCollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expandir.
        /// </summary>
        internal static string RadGridHierarchySettingsExpandTooltip {
            get {
                return ResourceManager.GetString("RadGridHierarchySettingsExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraer.
        /// </summary>
        internal static string RadGridHierarchySettingsSelfCollapseTooltip {
            get {
                return ResourceManager.GetString("RadGridHierarchySettingsSelfCollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expandir.
        /// </summary>
        internal static string RadGridHierarchySettingsSelfExpandTooltip {
            get {
                return ResourceManager.GetString("RadGridHierarchySettingsSelfExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar nuevo registro.
        /// </summary>
        internal static string RadGridMasterTableViewCommandItemSettingsAddNewRecordText {
            get {
                return ResourceManager.GetString("RadGridMasterTableViewCommandItemSettingsAddNewRecordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refresh.
        /// </summary>
        internal static string RadGridMasterTableViewCommandItemSettingsRefreshText {
            get {
                return ResourceManager.GetString("RadGridMasterTableViewCommandItemSettingsRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string RadGridMasterTableViewEditFormSettingsEditColumEditTexRadGridMasterTableViewCommandItemSettingsRefreshText {
            get {
                return ResourceManager.GetString("RadGridMasterTableViewEditFormSettingsEditColumEditTexRadGridMasterTableViewComma" +
                        "ndItemSettingsRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string RadGridMasterTableViewEditFormSettingsEditColumEditText {
            get {
                return ResourceManager.GetString("RadGridMasterTableViewEditFormSettingsEditColumEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string RadGridMasterTableViewEditFormSettingsEditColumnCancelText {
            get {
                return ResourceManager.GetString("RadGridMasterTableViewEditFormSettingsEditColumnCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar.
        /// </summary>
        internal static string RadGridMasterTableViewEditFormSettingsEditColumnFilterImageToolTip {
            get {
                return ResourceManager.GetString("RadGridMasterTableViewEditFormSettingsEditColumnFilterImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar.
        /// </summary>
        internal static string RadGridMasterTableViewEditFormSettingsEditColumnInsertText {
            get {
                return ResourceManager.GetString("RadGridMasterTableViewEditFormSettingsEditColumnInsertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string RadGridMasterTableViewEditFormSettingsEditColumnUpdateText {
            get {
                return ResourceManager.GetString("RadGridMasterTableViewEditFormSettingsEditColumnUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay registros para mostrar.
        /// </summary>
        internal static string RadGridMasterTableViewNoDetailRecordsText {
            get {
                return ResourceManager.GetString("RadGridMasterTableViewNoDetailRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay registros para mostrar.
        /// </summary>
        internal static string RadGridMasterTableViewNoMasterRecordsText {
            get {
                return ResourceManager.GetString("RadGridMasterTableViewNoMasterRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Pág: {4} &amp;nbsp;Pág actual {0} de {1}, items {2} a {3} de {5}..
        /// </summary>
        internal static string RadGridMasterTableViewPagerStylePagerTextFormat {
            get {
                return ResourceManager.GetString("RadGridMasterTableViewPagerStylePagerTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Págs. Siguientes.
        /// </summary>
        internal static string RadGridPagerStyleNextPagesToolTip {
            get {
                return ResourceManager.GetString("RadGridPagerStyleNextPagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pág. Siguiente.
        /// </summary>
        internal static string RadGridPagerStyleNextPageToolTip {
            get {
                return ResourceManager.GetString("RadGridPagerStyleNextPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Págs. Anteriores.
        /// </summary>
        internal static string RadGridPagerStylePrevPagesToolTip {
            get {
                return ResourceManager.GetString("RadGridPagerStylePrevPagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pág. Anterior.
        /// </summary>
        internal static string RadGridPagerStylePrevPageToolTip {
            get {
                return ResourceManager.GetString("RadGridPagerStylePrevPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenado Ascendente.
        /// </summary>
        internal static string RadGridSortingSettingsSortedAscToolTip {
            get {
                return ResourceManager.GetString("RadGridSortingSettingsSortedAscToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenado Descendente.
        /// </summary>
        internal static string RadGridSortingSettingsSortedDescToolTip {
            get {
                return ResourceManager.GetString("RadGridSortingSettingsSortedDescToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click aqui para ordenar.
        /// </summary>
        internal static string RadGridSortingSettingsSortToolTip {
            get {
                return ResourceManager.GetString("RadGridSortingSettingsSortToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando....
        /// </summary>
        internal static string RadGridStatusBarSettingsLoadingText {
            get {
                return ResourceManager.GetString("RadGridStatusBarSettingsLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listo.
        /// </summary>
        internal static string RadGridStatusBarSettingsReadyText {
            get {
                return ResourceManager.GetString("RadGridStatusBarSettingsReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://red-multipagos.com.co.
        /// </summary>
        internal static string SupportWebSiteURL {
            get {
                return ResourceManager.GetString("SupportWebSiteURL", resourceCulture);
            }
        }
    }
}
