//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartax.Web.Application.Modulos.Parametros.ReteICA
{


    public partial class FrmConceptos
    {
    }
}
