//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartax.Web.Application.Modulos.Parametros {
    
    
    public partial class FrmDesgloceICA {
        
        /// <summary>
        /// CtrlProvConfCliente1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Smartax.Web.Application.Controles.Parametros.Provision.CtrlConfClienteProv CtrlProvConfCliente1;
    }
}
